# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright Â© 2025 David Osipov  <personal@david-osipov.vision> (ORCID: 0009-0005-2713-9242, ISNI: 0000 0005 1802 960X)
# SPDXID: SPDXRef-File--dot-github-workflows-sbom-generator-yml
# FileType: SOURCE
#
# FileName: .github/workflows/sbom-generator.yml
# FileComment: Example GitHub Actions workflow for CI/CD or other automation for the meta-research repository.
# LicenseComments: Workflow configuration licensed under GPL-3.0-or-later.
name: Generate SBOM

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Or your default branch name
    paths-ignore:
      - 'sbom.spdx.json' # Ignore changes to the SBOM file itself

permissions:
  contents: write # Needed to commit back to the repository
  pull-requests: write # Needed to create the PR

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Set up Python
        uses: actions/setup-python@e348410e00f449ece8581cb8e88be8f0e7712da6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Cache apt packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-libmagic-${{ hashFiles('.github/workflows/sbom-generator.yml') }} # Key based on OS and this workflow file
          restore-keys: |
            ${{ runner.os }}-apt-libmagic-

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libmagic-dev jq

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sbom4files

      - name: Generate SBOM
        run: |
          sbom4files -d . -p "${{ github.repository }}" -r -i pyc,py,pyi --sbom spdx --format json -o sbom.spdx.json
          echo "SBOM generation completed."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@14576695c2f87fd4b34c70c3281d86036064ddda
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update SBOM' # Quoted to avoid YAML parsing issues
          committer: 'SBOM Generator <noreply@github.com>' # Quoted
          author: '${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>' # Quoted
          signoff: false
          branch: 'update-sbom' # Quoted for consistency
          delete-branch: true # Delete the branch once the PR is merged/closed
          title: 'Update SBOM' # Quoted
          body: |
            Automated SBOM update via GitHub Actions.

            This PR updates the `sbom.spdx.json` file.
          assignees: ${{ github.actor }}
          # reviewers: # Optional: Add reviewers
          # team-reviewers: # Optional: Add team reviewers
          # milestone: # Optional: Assign a milestone
          # draft: false # Set to true to create a draft PR
